/**
 * npm run icons  → app/icons/inline.generated.ts  (the icons Fyldo itself uses, bundled into app.js)
 *                 → app/icons/names.generated.ts   (every selectable icon name, for the Icon Picker modal chunk ONLY)
 * vite build     → assets/dist/icons/<key>.js      (every other Linear icon, loaded on demand; see buildIconModules)
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { moduleSource, normalizeIconName, renderAllLinear } from './lib.ts';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');

export async function writeInline(): Promise<number> {
  const wanted: string[] = JSON.parse(readFileSync(resolve(root, 'tools/icons/inline-icons.json'), 'utf8'));
  const all = new Map((await renderAllLinear()).map((i) => [i.key, i]));

  const entries = wanted.map((name) => {
    const icon = all.get(normalizeIconName(name));
    if (!icon) throw new Error(`inline-icons.json: unknown Iconsax icon "${name}"`);
    return `  ${JSON.stringify(icon.key)}: ${JSON.stringify(icon.nodes)},`;
  });

  const source =
    `/* AUTO-GENERATED by tools/icons/build.ts from iconsax-reactjs (Linear). DO NOT EDIT. */\n` +
    `import type { IconNode } from './types';\n\n` +
    `export const INLINE_ICONS: Record<string, IconNode[]> = {\n${entries.join('\n')}\n};\n`;

  mkdirSync(resolve(root, 'app/icons'), { recursive: true });
  writeFileSync(resolve(root, 'app/icons/inline.generated.ts'), source);
  // Every icon key Fyldo can load lazily: used by tests only (RTL-flip list check), never bundled.
  writeFileSync(resolve(root, 'tools/icons/all-keys.generated.json'), JSON.stringify([...all.keys()]) + '\n');

  // The Icon Picker lists every icon by its kebab name (the stored value). Imported by the modal chunk only, never by app.js.
  const kebabs = (await renderAllLinear()).map((i) => i.kebab).sort();
  const names =
    `/* AUTO-GENERATED by tools/icons/build.ts from iconsax-reactjs (Linear). DO NOT EDIT.\n` +
    ` * Imported ONLY by the lazily loaded Icon Picker modal, so it stays out of app.js. */\n\n` +
    `export const ICON_NAMES: readonly string[] = [\n${kebabs.map((k) => `  ${JSON.stringify(k)},`).join('\n')}\n];\n`;
  writeFileSync(resolve(root, 'app/icons/names.generated.ts'), names);
  return wanted.length;
}

/** Emit one ES module per icon into `outDir` (called from the Vite build). */
export async function buildIconModules(outDir: string): Promise<number> {
  const icons = await renderAllLinear();
  mkdirSync(outDir, { recursive: true });
  for (const icon of icons) writeFileSync(resolve(outDir, `${icon.key}.js`), moduleSource(icon.nodes));
  return icons.length;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  console.log(`icons: ${await writeInline()} inline icons generated`);
}
