/**
 * Directional icons that mirror under `[dir=rtl]` (CSS flip). Keys are normalised Iconsax names
 * (see normalize.ts). A test asserts every entry exists in the icon set. Vertical arrows, chevrons pointing up/down,
 * ticks, closes, search and settings never flip.
 */
export const RTL_FLIP: ReadonlySet<string> = new Set([
  'arrowleft',
  'arrowleft2',
  'arrowleft3',
  'arrowright',
  'arrowright2',
  'arrowright3',
  'arrowcircleleft',
  'arrowcircleleft2',
  'arrowcircleright',
  'arrowcircleright2',
  'arrowsquareleft',
  'arrowsquareright',
  'arrowrotateleft',
  'arrowrotateright',
  'back',
  'backsquare',
  'forward',
  'next',
  'previous',
  'backward',
  'sidebarleft',
  'sidebarright',
  'login',
  'logincurve',
  'logout',
  'logoutcurve',
  'directleft',
  'directright',
  'rotateleft',
  'rotateright',
  'refreshleftsquare',
  'refreshrightsquare',
  'textalignleft',
  'textalignright',
  'alignleft',
  'alignright',
  'documentforward',
  'documentprevious',
]);
