/**
 * Spot-checks the exported pack (design/figma/components/*.json) against numbers quoted in docs/design-spec.md §4.
 * Prints one line per check and exits 1 on any difference; it never edits either side. Run: node tools/figma/spot-check.mjs
 */
import { readFileSync } from 'node:fs';
const load = (k) => JSON.parse(readFileSync(`design/figma/components/${k}.json`, 'utf8'));
const find = (n, name) => { if (n.name === name) return n; for (const c of n.children ?? []) { const r = find(c, name); if (r) return r; } };
const path = (n, p) => p.reduce((x, name) => x && find(x, name), n);
const variant = (d, f, set) => d.variants.find((v) => Object.entries(set === 'icon-button' ? f : { Locale: 'EN', ...f }).every(([k, val]) => v.variantProperties[k] === val));
const rows = [];
const chk = (set, f, p, get, expected, ref) => {
  const d = load(set); const v = variant(d, f, set);
  let actual; try { const n = path(v.node, p); actual = n ? get(n, v.node) : 'LAYER NOT FOUND'; } catch (e) { actual = 'ERR ' + e.message; }
  rows.push({ set, variant: Object.values(f).join('/') || '-', layer: p.join('>') || '(root)', expected, actual, ok: JSON.stringify(actual) === JSON.stringify(expected), ref });
};
const H = (n) => n.height, W = (n) => n.width, R = (n) => n.cornerRadius, G = (n) => n.layout?.itemSpacing;
const PX = (n) => [n.layout.paddingLeft, n.layout.paddingRight], PY = (n) => [n.layout.paddingTop, n.layout.paddingBottom];
const P4 = (n) => [n.layout.paddingTop, n.layout.paddingRight, n.layout.paddingBottom, n.layout.paddingLeft];
const FX = (n) => n.effects?.style; const TS = (n) => n.text?.textStyle; const FILL = (n) => n.fills?.[0]?.token; const STROKE = (n) => n.strokes?.paints?.[0]?.token;
const B = { Type: 'Primary', State: 'Default' };
chk('button', { ...B, Size: 'Small' }, [], H, 32, '4.1 Small height 32');
chk('button', { ...B, Size: 'Medium' }, [], H, 40, '4.1 Medium height 40');
chk('button', { ...B, Size: 'Large' }, [], H, 48, '4.1 Large height 48');
chk('button', { ...B, Size: 'Large' }, [], R, 8, '4.1 Large radius md (8)');
chk('button', { ...B, Size: 'Small' }, [], PX, [12, 12], '4.1 Small padding-x 12');
chk('button', { ...B, Size: 'Large' }, ['Label'], TS, 'EN/Button/16', '4.1 Large text Button/16');
chk('button', { ...B, Size: 'Small' }, [], FILL, 'action/primary', '4.1 Primary fill action/primary');
chk('icon-button', { Type: 'Primary', State: 'Default', Size: 'Small' }, [], (n) => [n.width, n.height], [32, 32], '4.1 Icon Button 32 square');
chk('icon-button', { Type: 'Primary', State: 'Default', Size: 'Medium' }, [], (n) => [n.width, n.height], [40, 40], '4.1 Icon Button 40 square');
chk('icon-button', { Type: 'Primary', State: 'Default', Size: 'Large' }, [], R, 8, '4.1 Icon Button Large radius md');
chk('input', { Size: 'Small', State: 'Default' }, [], W, 320, '4.2 width 320');
chk('input', { Size: 'Medium', State: 'Default' }, ['Control'], H, 40, '4.2 Medium control 40');
chk('input', { Size: 'Large', State: 'Default' }, ['Control'], R, 8, '4.2 Large radius md');
chk('input', { Size: 'Small', State: 'Focus' }, ['Control'], FX, 'Focus/Input', '4.2 Focus effect');
chk('input', { Size: 'Small', State: 'Error' }, ['Control'], STROKE, 'status/error/solid', '4.2 Error stroke');
chk('textarea', { State: 'Default' }, ['Control'], H, 104, '4.3 default height 104');
chk('textarea', { State: 'Default' }, ['Control'], P4, [8, 12, 8, 12], '4.3 padding 12/8');
chk('textarea', { State: 'Default' }, [], W, 360, '4.3 width 360');
chk('toggle', { Size: 'Small', Checked: 'False', State: 'Default' }, ['Track'], (n) => [n.width, n.height], [28, 16], '4.4 Small track 28x16');
chk('toggle', { Size: 'Medium', Checked: 'False', State: 'Default' }, ['Track'], (n) => [n.width, n.height], [36, 20], '4.4 Medium track 36x20');
chk('toggle', { Size: 'Medium', Checked: 'False', State: 'Default' }, [], G, 12, '4.4 Medium gap to text 12');
chk('toggle', { Size: 'Small', Checked: 'False', State: 'Default' }, [], G, 8, '4.4 Small gap to text 8');
chk('checkbox', { Checked: 'False', State: 'Default' }, ['Box'], (n) => [n.width, n.height], [16, 16], '4.5 box 16x16');
chk('checkbox', { Checked: 'False', State: 'Default' }, ['Box'], R, 4, '4.5 radius xs');
chk('checkbox', { Checked: 'False', State: 'Default' }, [], G, 8, '4.5 gap 8');
chk('radio', { Checked: 'False', State: 'Default' }, ['Circle'], R, 9999, '4.5 radio full radius');
chk('radio', { Checked: 'True', State: 'Default' }, ['Circle'], (n) => [n.width, n.height], [16, 16], '4.5 circle 16');
chk('radio', { Checked: 'False', State: 'Default' }, ['Control'], H, 20, '4.5 slot 16x20');
chk('select', { Size: 'Small', State: 'Default' }, ['Control'], H, 32, '4.6 Small control 32');
chk('select', { Size: 'Large', State: 'Default' }, ['Control'], H, 48, '4.6 Large control 48');
chk('select', { Size: 'Small', State: 'Default' }, ['Chevron'], (n) => n.icon.size, 16, '4.6 chevron 16');
chk('select-menu', { Type: 'Single' }, [], R, 12, '4.6 radius lg');
chk('select-menu', { Type: 'Single' }, [], P4, [4, 4, 4, 4], '4.6 padding 4');
chk('select-menu', { Type: 'Single' }, [], FX, 'Shadow/Medium', '4.6 Shadow/Medium');
chk('menu-item', { Type: 'Single', State: 'Default' }, [], H, 36, '4.6 height 36');
chk('menu-item', { Type: 'Single', State: 'Default' }, [], P4, [8, 8, 8, 8], '4.6 padding 8');
chk('menu-item', { Type: 'Single', State: 'Hover' }, [], FILL, 'surface/default', '4.6 hover fill surface/default');
chk('multi-select', { Size: 'Small', State: 'Default' }, ['Control'], H, 34, '4.7 min height 34');
chk('multi-select', { Size: 'Medium', State: 'Default' }, ['Control'], H, 42, '4.7 min height 42');
chk('multi-select', { Size: 'Large', State: 'Default' }, ['Control'], H, 50, '4.7 min height 50');
chk('tag', { Size: 'Small', State: 'Default' }, [], H, 20, '4.7 Small 20');
chk('tag', { Size: 'Medium', State: 'Default' }, [], H, 24, '4.7 Medium 24');
chk('tag', { Size: 'Small', State: 'Default' }, [], R, 4, '4.7 radius xs');
chk('badge', { Tone: 'Gray', Style: 'Subtle', Size: 'Small' }, [], H, 20, '4.8 Small 20');
chk('badge', { Tone: 'Gray', Style: 'Subtle', Size: 'Medium' }, [], H, 24, '4.8 Medium 24');
chk('badge', { Tone: 'Gray', Style: 'Subtle', Size: 'Medium' }, [], PX, [8, 8], '4.8 Medium padding-x 8');
chk('notice', { Tone: 'Gray' }, [], P4, [12, 16, 12, 16], '4.8 padding 16/12');
chk('notice', { Tone: 'Gray' }, [], G, 12, '4.8 gap 12');
chk('notice', { Tone: 'Red' }, [], FILL, 'status/error/bg', '4.8 Red fill status/error/bg');
chk('nav-item', { State: 'Default' }, [], H, 32, '4.9 height 32');
chk('nav-item', { State: 'Default' }, [], P4, [6, 8, 6, 8], '4.9 padding 8/6');
chk('nav-item', { State: 'Active' }, [], FILL, 'surface/active', '4.9 Active fill');
chk('sidebar', {}, [], W, 256, '4.9 width 256');
chk('sidebar', {}, ['Header'], H, 60, '4.9 header 60');
chk('sidebar', {}, ['Navigation'], G, 20, '4.9 group gap 20');
chk('tab', { State: 'Default' }, [], H, 48, '4.10 height 48');
chk('tab', { State: 'Default' }, ['Content'], H, 32, '4.10 inner 32');
chk('tab', { State: 'Default' }, ['Indicator'], H, 2, '4.10 indicator 2');
chk('tabs', {}, [], W, 800, '4.10 width 800');
chk('tabs', {}, [], G, 4, '4.10 gap 4');
chk('tabs', {}, ['Divider'], H, 1, '4.10 1 px bottom divider');
chk('top-navigation', {}, ['Header'], H, 48, '4.10 row 1 height 48');
chk('top-navigation', {}, ['Header'], PY, [12, 4], '4.10 row 1 padding top 12 / bottom 4');
chk('top-navigation', {}, ['Navigation'], H, 48, '4.10 row 2 height 48');
chk('setting-row', { Layout: 'Inline' }, [], PY, [20, 20], '4.11 padding-y 20');
chk('setting-row', { Layout: 'Inline' }, [], G, 32, '4.11 Inline gap 32');
chk('setting-row', { Layout: 'Stacked' }, [], G, 12, '4.11 Stacked gap 12');
chk('section-card', { Tone: 'Default' }, [], W, 800, '4.11 width 800');
chk('section-card', { Tone: 'Default' }, [], R, 12, '4.11 radius lg');
chk('section-card', { Tone: 'Default' }, ['Header'], G, 6, '4.11 header gap 6');
chk('save-bar', { State: 'Dirty' }, [], W, 800, '4.12 width 800');
chk('save-bar', { State: 'Dirty' }, [], H, 54, '4.12 height 54');
chk('save-bar', { State: 'Dirty' }, [], FX, 'Shadow/Medium', '4.12 Shadow/Medium');
chk('page-header', {}, [], G, 24, '4.12 gap 24');
chk('page-header', {}, ['Title'], TS, 'EN/Heading/32', '4.12 Heading/32');
chk('page-header', {}, ['Text'], G, 6, '4.12 text gap 6');
chk('modal', { Type: 'Default' }, [], W, 480, '4.13 width 480');
chk('modal', { Type: 'Default' }, [], FX, 'Shadow/Large', '4.13 Shadow/Large');
chk('modal', { Type: 'Default' }, ['Footer'], P4, [16, 24, 16, 24], '4.13 footer padding 24/16');
chk('tooltip', { Placement: 'Top' }, ['Bubble'], R, 6, '4.13 bubble radius sm');
chk('tooltip', { Placement: 'Top' }, ['Label'], (n) => n.layout.maxWidth, 240, '4.13 max width 240 (on the Label text)');
chk('tooltip', { Placement: 'Top' }, ['Arrow'], (n) => [n.width, n.height], [10, 5], '4.13 arrow 10x5');
chk('toast', { Tone: 'Neutral' }, [], W, 400, '4.13 width 400');
chk('toast', { Tone: 'Neutral' }, [], G, 12, '4.13 gap 12');
chk('toast', { Tone: 'Neutral' }, [], R, 12, '4.13 radius lg');
chk('empty-state', { Size: 'Large' }, [], W, 480, '4.13 Large width 480');
chk('empty-state', { Size: 'Small' }, [], W, 360, '4.13 Small width 360');
chk('empty-state', { Size: 'Large' }, ['Icon box'], W, 48, '4.13 Large icon box 48');
chk('empty-state', { Size: 'Small' }, ['Icon box'], W, 40, '4.13 Small icon box 40');
chk('empty-state', { Size: 'Large' }, [], G, 20, '4.13 Large gap 20');
for (const r of rows) console.log(`${r.ok ? 'ok  ' : 'DIFF'} ${r.set.padEnd(15)} ${r.variant.padEnd(22)} ${r.layer.padEnd(16)} exp ${JSON.stringify(r.expected)} got ${JSON.stringify(r.actual)}  [${r.ref}]`);
const diffs = rows.filter((r) => !r.ok).length;
console.log(diffs, 'diffs of', rows.length);
process.exitCode = diffs ? 1 : 0;
